Repository vives-dust/framework, pull requests merged in 2022-10, with the labels that each got.

#24 Grafana dashboard
  docker-compose.dev.yml
  docker-compose.yml
  grafana/dashboards/dust.json
  grafana/provisioning/datasources/all.yml
Labels: bug, enhancement

#31 added the dashboards for provisioning on grafana
  grafana/dashboards/correlations.json
  grafana/dashboards/devbit-weatherstation.json
  grafana/dashboards/dust.json
  grafana/dashboards/weatherapi.json
Labels: enhancement

#34 Api docs fix
  api-docs/Dockerfile
  api-docs/README.md
  api-docs/docs-docker/favicon.png
  api-docs/docs-docker/index.html
  api-docs/docs/index.html
  api-docs/openapi/info-description.md
  api-docs/openapi/openapi.yaml
  api-docs/package-lock.json
Labels: bug

#38 corrected regex for trailing slash bug in yaml file
  docker-compose.yml
Labels: bug
